'use client'
import React, { useEffect } from 'react'
import QseDocEditor from '@/components/features/qse/QseDocEditor'

const DOC_ID = 'QSE-8.1-TEMP-ITP'

const defaultHtml = `
<div class="prose prose-slate max-w-none">
  <div class="grid grid-cols-3 gap-4 mb-8 text-sm">
    <div class="border p-3"><span class="font-semibold">Document ID:</span> QSE-8.1-TEMP-ITP</div>
    <div class="border p-3"><span class="font-semibold">Revision:</span> A</div>
    <div class="border p-3"><span class="font-semibold">Effective Date:</span> [Enter Date]</div>
  </div>
  <h3 class="mt-8 mb-4">1.0 ITP Information</h3>
  <div class="overflow-x-auto mb-8">
    <table class="min-w-full border border-gray-300 text-sm">
      <tbody>
        <tr><td class="border p-2 font-semibold w-1/4">Project Name:</td><td class="border p-2">[Enter Project Name]</td></tr>
        <tr><td class="border p-2 font-semibold">ITP Number:</td><td class="border p-2">[Auto-generated by ITP Agent]</td></tr>
        <tr><td class="border p-2 font-semibold">Work Package/Lot ID:</td><td class="border p-2">[Linked to Lot Register]</td></tr>
        <tr><td class="border p-2 font-semibold">Specification Reference:</td><td class="border p-2">[Enter specification section]</td></tr>
        <tr><td class="border p-2 font-semibold">QA Engineer:</td><td class="border p-2">[Enter QA Engineer]</td></tr>
      </tbody>
    </table>
  </div>
  <h3 class="mt-8 mb-4">2.0 Scope of Work</h3>
  <p>This ITP covers the following activities and deliverables:</p>
  <ul>
    <li>[Enter specific work activities covered by this ITP]</li>
    <li>[Enter specific deliverables and quality criteria]</li>
    <li>[Enter applicable standards and specifications]</li>
  </ul>
  <h3 class="mt-8 mb-4">3.0 Inspection & Test Schedule</h3>
  <div class="overflow-x-auto mb-8">
    <table class="min-w-full border border-gray-300 text-sm">
      <thead class="bg-gray-50">
        <tr>
          <th class="border p-2 text-left">Activity</th>
          <th class="border p-2 text-left">Inspection Point</th>
          <th class="border p-2 text-left">Test/Criteria</th>
          <th class="border p-2 text-left">Hold Point</th>
          <th class="border p-2 text-left">Responsible Party</th>
          <th class="border p-2 text-left">Records</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="border p-2">[Enter construction activity]</td>
          <td class="border p-2">[Enter when inspection occurs]</td>
          <td class="border p-2">[Enter test method/acceptance criteria]</td>
          <td class="border p-2">[Yes/No - requires approval to proceed]</td>
          <td class="border p-2">[Enter responsible party - Contractor/Client/Independent]</td>
          <td class="border p-2">[Enter required documentation]</td>
        </tr>
      </tbody>
    </table>
  </div>
  <h3 class="mt-8 mb-4">4.0 Material Testing Requirements</h3>
  <div class="overflow-x-auto mb-8">
    <table class="min-w-full border border-gray-300 text-sm">
      <thead class="bg-gray-50">
        <tr>
          <th class="border p-2 text-left">Material</th>
          <th class="border p-2 text-left">Test Method</th>
          <th class="border p-2 text-left">Frequency</th>
          <th class="border p-2 text-left">Acceptance Criteria</th>
          <th class="border p-2 text-left">Testing Laboratory</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="border p-2">[Enter material type]</td>
          <td class="border p-2">[Enter test standard - e.g., AS 1289.3.6.1]</td>
          <td class="border p-2">[Enter test frequency]</td>
          <td class="border p-2">[Enter acceptance criteria]</td>
          <td class="border p-2">[Enter NATA accredited laboratory]</td>
        </tr>
      </tbody>
    </table>
  </div>
  <h3 class="mt-8 mb-4">5.0 Documentation Requirements</h3>
  <ul>
    <li>Material certificates and compliance statements</li>
    <li>Test certificates from accredited laboratories</li>
    <li>Inspection checklists and photographs</li>
    <li>Non-conformance reports (if applicable)</li>
    <li>As-built drawings (where applicable)</li>
    <li>Manufacturer warranties and installation certificates</li>
  </ul>
  <h3 class="mt-8 mb-4">6.0 Non-Conformance Management</h3>
  <ul>
    <li>Immediate notification via the system's NCR module</li>
    <li>Root cause analysis and corrective action planning</li>
    <li>Re-inspection and testing following corrective actions</li>
    <li>Close-out verification and documentation</li>
    <li>Lessons learned integration into future ITPs</li>
  </ul>
  <h3 class="mt-8 mb-4">7.0 Hold Point Management</h3>
  <div class="overflow-x-auto mb-8">
    <table class="min-w-full border border-gray-300 text-sm">
      <thead class="bg-gray-50">
        <tr>
          <th class="border p-2 text-left">Hold Point</th>
          <th class="border p-2 text-left">Approval Authority</th>
          <th class="border p-2 text-left">Notification Method</th>
          <th class="border p-2 text-left">Required Lead Time</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="border p-2">[Enter hold point description]</td>
          <td class="border p-2">[Enter approval authority]</td>
          <td class="border p-2">[Automatic system notification]</td>
          <td class="border p-2">[Enter required notice period]</td>
        </tr>
      </tbody>
    </table>
  </div>
  <h3 class="mt-8 mb-4">8.0 Digital Execution</h3>
  <ul>
    <li><strong>Tablet-Based Inspection:</strong> Real-time data entry and photo capture</li>
    <li><strong>GPS Location Tracking:</strong> Automatic location stamping for inspections</li>
    <li><strong>Digital Signatures:</strong> Electronic sign-off by authorized personnel</li>
    <li><strong>Automatic Notifications:</strong> Alerts for hold points and non-conformances</li>
    <li><strong>Real-Time Reporting:</strong> Live dashboard updates and progress tracking</li>
  </ul>
</div>`

function TemplateInitializer() {
  useEffect(() => {
    let mounted = true
    ;(async () => {
      const res = await fetch(`/api/qse/${encodeURIComponent(DOC_ID)}/fetch`)
      if (!mounted) return
      if (!res.ok) return
      const json = await res.json()
      const existing = (json?.content?.html || json?.content?.body || '').trim()
      if (!existing) {
        await fetch(`/api/qse/${encodeURIComponent(DOC_ID)}/save`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ html: defaultHtml }),
        })
      }
    })()
    return () => { mounted = false }
  }, [])
  return null
}

export default function ItpTemplatePage() {
  return (
    <div className="max-w-5xl mx-auto space-y-4">
      <h1 className="text-2xl font-semibold mb-4">Inspection & Test Plan (ITP) Template</h1>
      <TemplateInitializer />
      <QseDocEditor docId={DOC_ID} />
    </div>
  )
}


